### PR TITLE
Report compilation errors about incomplete types

### LINKED ISSUE #2844: Incomplete struct types
The following examples are crashed:

```ispc
struct S1 { struct S2 a; };
struct S1 func() {
    struct S1 x;
    return x;
}
```

```ispc
struct Sx bar() {}
```

```ispc
int boo(struct Sy) {}
```

```ispc
int foo() { struct Sx x; }
```

I guess the reason for all of them is same. By some reason, ISPC doesn't check the usage of incomplete structs types on AST level. So, LLVM IR is incorrect:
```llvm-ir
Cannot allocate unsized type
  %7 = alloca %v4_varying_Sx, align 8
LLVM ERROR: Broken module found, compilation aborted!
```

This example is compiled but shouldn't. It has to generate the compiler error "error: field 'a' has incomplete type 'S2'"
```ispc
struct S1 { struct S2 a; };
```

### PR DESCRIPTION
**Pull request by nurmukhametov**
This fixes #2844 and #478.

This change adds error reports for incomplete types in various situations:
- return values of functions
- parameters of functions
- variable declaration and initialization

### CODE REVIEW

File: src/type.cpp [hunk 1]
```diff
@@ -1503,6 +1511,8 @@ bool ArrayType::IsBoolType() const { return false; }
 
 bool ArrayType::IsConstType() const { return child ? child->IsConstType() : false; }
 
+bool ArrayType::IsCompleteType() const { return GetBaseType()->IsCompleteType(); }
```
Comment (aneshlya) [inline src/type.cpp:1514]: We have an unsized arrays which I think are also incomplete types.

File: tests/lit-tests/2844-1.ispc [hunk 2]
```diff
@@ -0,0 +1,14 @@
...
+// RUN: not %{ispc} --target=host --nowrap --nostdlib %s -o %t.o 2>&1 | FileCheck %s
+
+// CHECK: Error: return type is an incomplete type: varying struct Sx
+struct Sx bar() {}
+
+// CHECK-NOT: Error: return type is an incomplete type: varying struct Sy
+struct Sy foo();
+
+// CHECK-NOT: Error: return type is an incomplete type: varying struct Sz
+struct Sz func();
```
Comment (aneshlya) [inline tests/lit-tests/2844-1.ispc:12]: What is the difference between these two?

File: tests/lit-tests/2844-3.ispc [hunk 3]
```diff
@@ -0,0 +1,17 @@
+// Check that we catch incomplete struct types in variable definitions
+
+// RUN: not %{ispc} --target=host --nowrap --nostdlib %s -o %t.o 2>&1 | FileCheck %s
+
+// CHECK: Error: type struct 'Sx' is incomplete and cannot be initialized
+// CHECK: Error: variable 'x' has initializer but incomplete struct type
+int foo() { struct Sx x = { 0 }; }
+// CHECK: Error: type struct 'Sy' is incomplete and cannot be declared
+// CHECK: Error: variable 'y' has incomplete struct type and cannot be defined
```
Comment (aneshlya) [inline tests/lit-tests/2844-3.ispc:9]: Can be here a case when one error is reported and the other is not? Feels like we only need on error message instead of two. It would be the same behavior as in C++.

File: src/func.cpp [hunk 4]
```diff
@@ -206,6 +206,21 @@ Function::Function(Symbol *s, Stmt *c, Symbol *ms, std::vector<Symbol *> &a)
...
+    const Type *retType = GetType()->GetReturnType();
+    const FunctionType *funcType = GetType();
+    if (!retType->IsCompleteType()) {
+        Error(funcType->GetSourcePos(), "return type is an incomplete type: %s", retType->GetString().c_str());
+    }
+
+    for (int i = 0; i < funcType->GetNumParameters(); i++) {
+        const Type *paramType = funcType->GetParameterType(i);
+        const SourcePos &pos = funcType->GetParameterSourcePos(i);
+        const std::string &paramName = funcType->GetParameterName(i);
```
[the remark this answers is not in the document]
Comment (nurmukhametov) [reply src/func.cpp]: Done

File: src/type.cpp (hunk 1 above)
Comment (nurmukhametov) [reply src/type.cpp:1514]: I think that, generally, unsized arrays should not be considered incomplete types unless they are the only members of a struct.

File: tests/lit-tests/2844-1.ispc (hunk 2 above)
Comment (nurmukhametov) [reply tests/lit-tests/2844-1.ispc]: No idea, I have removed the second copy.

File: tests/lit-tests/2844-3.ispc (hunk 3 above)
Comment (nurmukhametov) [reply tests/lit-tests/2844-3.ispc]: I have removed the first report.

**Review by aneshlya — APPROVED** [review]
Looks good to me!

File: src/type.cpp [hunk 5]
```diff
@@ -742,6 +744,8 @@ bool TemplateTypeParmType::IsSignedType() const { return false; }
 
 bool TemplateTypeParmType::IsConstType() const { return isConst; }
 
+bool TemplateTypeParmType::IsCompleteType() const { return false; }
```
Comment (dbabokin) [inline src/type.cpp:747]: I don't really understand how this works with templates / template paramters.

Would be good to have a test that checks that the same errors are properly reported when the same happens for function instantiation - i.e. wrt function parameters and return types.

Comment (nurmukhametov) [reply src/type.cpp:747]: I have added a test to check template instantiation with an incomplete struct type.

Comment (dbabokin) [reply src/type.cpp:747]: The tests look good, thank you!

**Review by dbabokin — APPROVED** [review]
LGTM
