### PR TITLE
Fix nested template without arguments

### LINKED ISSUE #2825: Compiler crash when nested template function doesn't use templated argument
This issue was discovered in https://github.com/ispc/ispc/pull/2790#issuecomment-2032512084.
Nested template (`foo2`) without templated arguments https://ispc.godbolt.org/z/fe9szMa4v - breaks.
Nested template (`foo2`) withtemplated arguments https://ispc.godbolt.org/z/eK8j1bqcq - works.

When function has templated arguments, we check it in ResolveOverloads https://github.com/ispc/ispc/blob/main/src/expr.cpp#L8900 and return earlier before doing `AddInstantiation`. If not, we continue executing the function and create a new instantiation, but it's too earlier for that.

### PR DESCRIPTION
**Pull request by aneshlya**
Fixes #2825 and #3354.

### CODE REVIEW

**Review by dbabokin — APPROVED** [review]
LGTM

File: src/expr.cpp [hunk 1]
```diff
@@ -9708,13 +9708,36 @@ bool FunctionSymbolExpr::ResolveOverloads(SourcePos argPos, const std::vector<co
...
+    bool hasDependentTemplateArgs = false;
+    for (const auto &arg : templateArgs) {
+        if (arg.IsType()) {
+            if (arg.GetAsType() && arg.GetAsType()->IsDependent()) {
+                hasDependentTemplateArgs = true;
+                break;
+            }
+        } else if (arg.IsNonType()) {
+            const ConstExpr *ce = arg.GetAsConstExpr();
+            // template argument is nor resolved yet
```
Comment (nurmukhametov) [inline src/expr.cpp:9730]: not

**Review by nurmukhametov — APPROVED** [review]
LGTM

File: src/expr.cpp (hunk 1 above)
Comment (aneshlya) [reply src/expr.cpp]: Fixed
