### PR TITLE
Fix of several crashes related to short vector initialization/indexing

### LINKED ISSUE #3484: ISPC fails to handle case when function with varying return type is used to initialize uniform variable
This is the way to trigger ISPC crash:
```ISPC
static varying float load(const uniform float *values) { return 0.0f; }

export void func(uniform float values[][programCount])
{
    uniform float<3> col_xyz = {load(&values[0][0]),
                                load(&values[0][0]),
                                load(&values[0][0])};
}
```

Godbolt example: https://godbolt.org/z/37TE8jb5Y

### PR DESCRIPTION
**Pull request by aneshlya**
## Description
Fixed three separate compiler crashes that occurred when processing invalid or edge-case ISPC code related to short vectors.
1. Use ISPC's `symVectorType->LLVMType(g->ctx)` instead of manually constructing `llvm::FixedVectorType::get()`
2. Null pointer check (src/expr.cpp:4831)
3. Use PointerType::GetVarying() when indexType->IsVaryingType()
4. Early exit if we can't construct short vector from initializer list due to different variability.

## Related Issue
- [x] Fixes #3484, #2376 

## Checklist
- [x] Code has been formatted with `clang-format` (e.g., `clang-format -i src/ispc.cpp`)
- [x] Git history has been squashed to meaningful commits (one commit per logical change)
- [x] Compiler changes are covered by [lit tests](https://github.com/ispc/ispc/tree/main/tests/lit-tests)
- [ ] Language/stdlib changes include new [functional tests](https://github.com/ispc/ispc/tree/main/tests/func-tests) for runtime behavior
- [ ] [Documentation](https://github.com/ispc/ispc/tree/main/docs/ispc.rst) updated if needed

### CODE REVIEW

File: src/expr.cpp [hunk 1]
```diff
@@ -941,6 +939,11 @@ void ispc::InitSymbol(AddressInfo *ptrInfo, const Type *symType, Expr *initExpr,
 
                             // Make type conversion
                             if (!Type::EqualIgnoringConst(symType, vResType)) {
+                                // Early return for unsupported conversions (e.g., varying to uniform)
+                                if (symVectorType->IsUniformType() && vResType->IsVaryingType()) {
```
[the remark this answers is not in the document]
Comment (aneshlya) [reply src/expr.cpp:943]: This will be caught later by semantic analysis

File: src/expr.cpp [hunk 2]
```diff
@@ -4987,7 +4996,12 @@ llvm::Value *IndexExpr::GetValue(FunctionEmitContext *ctx) const {
             Assert(m->errorCount > 0);
             return nullptr;
         }
-        lvType = PointerType::GetUniform(st->GetElementType());
+        // Use varying pointer type if the index is varying, uniform otherwise
+        if (indexType->IsVaryingType()) {
+            lvType = PointerType::GetVarying(st->GetElementType());
+        } else {
+            lvType = PointerType::GetUniform(st->GetElementType());
+        }
```
Comment (nurmukhametov) [inline src/expr.cpp:5004]: This fixes #2376, but it suggests a different expected behavior (produce an error and exit nicely), so I am confused.

Comment (aneshlya) [reply src/expr.cpp:5004]: Right, the issue description was not correct, I've updated it. It's valid code and ispc should be able to compile it.
