### PR TITLE
Fix select-short-vec.ispc for targets with i8 mask

### LINKED ISSUE #3491: Test select-short-vec is failing accross platforms on neon-i8x16 with -O1
https://github.com/ispc/ispc/actions/runs/16286474415/job/45986562102#step:6:3066
```
Test ./tests/func-tests/select-short-vec.ispc failed (return code 1)            
./tests/func-tests/select-short-vec.ispc.run: value 0 disagrees: returned 2.000000 [0x1p+1], expected 0.000000 [0x0p+0]
./tests/func-tests/select-short-vec.ispc.run: value 2 disagrees: returned 2.000000 [0x1p+1], expected 0.000000 [0x0p+0]
./tests/func-tests/select-short-vec.ispc.run: value 3 disagrees: returned 2.000000 [0x1p+1], expected 0.000000 [0x0p+0]
./tests/func-tests/select-short-vec.ispc.run: value 4 disagrees: returned 2.000000 [0x1p+1], expected 0.000000 [0x0p+0]
./tests/func-tests/select-short-vec.ispc.run: value 6 disagrees: returned 2.000000 [0x1p+1], expected 0.000000 [0x0p+0]
./tests/func-tests/select-short-vec.ispc.run: value 8 disagrees: returned 2.000000 [0x1p+1], expected 0.000000 [0x0p+0]
./tests/func-tests/select-short-vec.ispc.run: value 10 disagrees: returned 2.000000 [0x1p+1], expected 0.000000 [0x0p+0]
./tests/func-tests/select-short-vec.ispc.run: value 12 disagrees: returned 2.000000 [0x1p+1], expected 0.000000 [0x0p+0]
./tests/func-tests/select-short-vec.ispc.run: value 13 disagrees: returned 2.000000 [0x1p+1], expected 0.000000 [0x0p+0]
./tests/func-tests/select-short-vec.ispc.run: value 14 disagrees: returned 2.000000 [0x1p+1], expected 0.000000 [0x0p+0]
```

### PR DESCRIPTION
**Pull request by nurmukhametov**
## Description

This PR fixes #3491 properly. With this fix nightly tests should pass [link](https://github.com/ispc/ispc/actions/runs/16624470651). However in full testing, there are still failed jobs with, e.g, avx1-i32x16 for -O1 for LLVM <= 19 [link](https://github.com/ispc/ispc/actions/runs/16624474802).

This PR changes:

* Gather missed conversion of bool to storage type for targets with i8 mask.

* This also fixes FunctionEmitContext::lSwitchBoolSize_2 to be able to cast bool <-> mask of equal length to each other, i.e., performing either 0x01 -> 0xff or 0xff -> 0x01 conversion.

* maskedStore: convert only bool to bool storage representation. Plain int8 or uint8 do not to be represented or converted like bool types.

### Debugging utilities:
* Added debug wrapper functions (`dv` and `dt`) for dumping LLVM values and types in debug builds, aiding GDB/LLDB debugging.

### Reverted workaround:
* https://github.com/ispc/ispc/commit/d22999b8cc152af7edf685bc86acd748405add2e

## Related Issue
- [X] Linked to relevant issue: #3491 and #3513

## Checklist
- [X] Code has been formatted with `clang-format` (e.g., `clang-format -i src/ispc.cpp`)
- [X] Git history has been squashed to meaningful commits (one commit per logical change)

### CODE REVIEW

File: src/ctx.cpp [hunk 1]
```diff
@@ -2903,6 +2906,7 @@ llvm::Value *FunctionEmitContext::gather(llvm::Value *ptr, const PointerType *pt
 
     // bool type is stored as i8. So, it requires some processing.
     if (returnType->IsBoolType()) {
+        // TODO!: should we just call SwitchBoolToStorageType here unconditionally?
```
Comment (aneshlya) [inline src/ctx.cpp]: Yeah, I think this logic should be consolidated in `SwitchBoolToMaskType`. If you can spend a little more time on it, it would be good to 
1. resolve this TODO
2. describe all the bool/mask conversion behavior in design document

File: src/ctx.cpp [hunk 2]
```diff
@@ -3178,7 +3178,10 @@ void FunctionEmitContext::maskedStore(llvm::Value *value, llvm::Value *ptr, cons
         maskedStoreFunc = m->module->getFunction(builtin::__pseudo_masked_store_i16);
     } else if (llvmValueStorageType == LLVMTypes::Int8VectorType) {
         maskedStoreFunc = m->module->getFunction(builtin::__pseudo_masked_store_i8);
-        value = SwitchBoolToStorageType(value, llvmValueStorageType);
+        // Do not mix i8 types with bool type, only bool type requires the special handling.
+        if (valueType->IsBoolType()) {
```
Comment (aneshlya) [inline src/ctx.cpp:3164]: Consider adding a `valueType` parameter to `SwitchBoolToStorageType`. This would allow us to perform an early return if the function receives a type other than bool, which could help prevent potential issues with future usage

File: tests/lit-tests/3513.ispc [hunk 3]
```diff
@@ -0,0 +1,41 @@
+// This test checks whether ISPC produces correct representation of bool type
+// on ABI boundary for targets with i8 masks.
+
+// RUN: %{ispc} --pic --target=sse4.1-i8x16 -h %t.h %s -o %t.o
```
Comment (zephyr111) [inline tests/lit-tests/3513.ispc]: I think it would be good to test more targets. For example one that is not i8, and maybe an AVX-512 like avx512skl-x16 and/or avx512skl-x64 (I wonder what is the value of `g->target->getMaskBitCount()` in this case).

File: stdlib/include/short_vec.isph [hunk 4]
```diff
@@ -166,7 +166,7 @@ template <typename T, uint N> inline uniform T<N> select(uniform bool cond, unif
     uniform T<N> result;
 
     foreach (i = 0 ... N) {
-        result[i] = select((UIntMaskType)cond, t[i], f[i]);
+        result[i] = select(cond, t[i], f[i]);
```
Comment (zephyr111) [inline stdlib/include/short_vec.isph:169]: This is great!

File: src/ctx.cpp [hunk 5]
```diff
@@ -2920,6 +2924,9 @@ llvm::Value *FunctionEmitContext::gather(llvm::Value *ptr, const PointerType *pt
         } else if (g->target->getDataLayout()->getTypeSizeInBits(returnType->LLVMStorageType(g->ctx)) >
                    g->target->getDataLayout()->getTypeSizeInBits(llvmReturnType)) {
             gatherCall = TruncInst(gatherCall, llvmReturnType);
+        } else {
+            gatherCall =
```
Comment (zephyr111) [inline src/ctx.cpp]: I think it should be good to have a lit-test with gathers since they are impacted here.

By the way, is there a scatter operation somewhere in ISPC? If yes, it might be impacted too.

File: src/ctx.cpp (hunk 1 above)
Comment (zephyr111) [inline src/ctx.cpp]: I am not sure to fully understand the logic of the whole code, but won't this cause an issue if we call a function and use the result as a mask (like with `select(test(), a, b)`) ? Maybe it is safe because the bool (with a "bool storage type") will then be converted back to a mask?

I think it would be good to add a lit-test with many booleans operations (and function call returning boolean), just to be on the safe side. Ideally, something tested with both i8 and non-i8 targets.

**Review by zephyr111 — CHANGES_REQUESTED** [review]
Thank you. This is great. 
I added some (certainly naive) remarks and questions. 
Overall, I think more lit-tests are needed.

By the way, does this PR impacts the behaviour of casts from/to boolean?

File: tests/lit-tests/3513.ispc (hunk 3 above)
Comment (nurmukhametov) [reply tests/lit-tests/3513.ispc]: Indeed, it makes sense. To test more targets, I either need to create a lit configuration command (to avoid a lot of copy-paste), or somehow test in func-tests.

For all avx512 targets, the mask bit count is 1.

File: src/ctx.cpp (hunk 5 above)
Comment (nurmukhametov) [reply src/ctx.cpp]: gathers and scatters are generated in this test. You can inspect the initial LLVM IR generated for the user code in `pre*GenerateIR*.ll` file that can be obtained via this command inside the directory `dbg`:
```bash
$ ispc --target=host input.ispc --no-discard-value-names --debug-phase=pre:last --dump-file=dbg
```

Actually, all three fixes from this PR are required to fix this test.

File: src/ctx.cpp (hunk 1 above)
Comment (nurmukhametov) [reply src/ctx.cpp]: I have added test like that in `tests/func-tests/select-short-vec-func.ispc`. Apparently, it triggers a crash in macos linker e.g., [here](https://github.com/ispc/ispc/actions/runs/16750557498/job/47421333173) :
```bash
Compilation of test ./tests/func-tests/select-short-vec-func.ispc failed            
0  0x103360c3b  __assert_rtn + 64
1  0x10332c3c6  ld::AtomFileConsolidator::addAtomFile(ld::AtomFile const*, ld::AtomFile const*, bool) + 9446
2  0x10333a198  ld::AtomFileConsolidator::addAtomFile(ld::AtomFile const*) + 136
3  0x10335efb9  ld::pass::stubs(ld::Options const&, ld::AtomFileConsolidator&) + 1801
4  0x103343d94  ld::AtomFileConsolidator::resolve() + 19828
5  0x1032ac5e8  main + 12552
ld: Assertion failed: (slot < _sideTableBuffer.size()), function addAtom, file AtomFileConsolidator.cpp, line 2278.
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

File: tests/lit-tests/3513.ispc (hunk 3 above)
Comment (nurmukhametov) [reply tests/lit-tests/3513.ispc]: I tested more targets but not all, see the comment in `tests/lit-tests/3513.ispc` under TODO.

File: src/ctx.cpp (hunk 2 above)
Comment (nurmukhametov) [reply src/ctx.cpp:3164]: I didn't find in some cases the proper `valueType` in the caller context.

File: src/ctx.cpp (hunk 1 above)
Comment (nurmukhametov) [reply src/ctx.cpp]: TODO is resolved here: https://github.com/ispc/ispc/pull/3518/commits/39395099e7f204bd4dabbadb24e364549789fbe4

File: tests/lit-tests/3513.ispc [hunk 6]
```diff
@@ -0,0 +1,117 @@
...
+// RUN: %{cc} -O2 -x c -c %s -o %t-sse4.1-i8x16.c.o --include %t-sse4.1-i8x16.h
+// RUN: %{cc} %t-sse4.1-i8x16.o %t-sse4.1-i8x16.c.o -o %t-sse4.1-i8x16.c.bin
+// RUN: %t-sse4.1-i8x16.c.bin | FileCheck %s
+// RUN: %{cc} -O2 -x c++ -c %s -o %t-sse4.1-i8x16.cpp.o --include %t-sse4.1-i8x16.h
+// RUN: %{cc} %t-sse4.1-i8x16.o %t-sse4.1-i8x16.cpp.o -o %t-sse4.1-i8x16.cpp.bin
+// RUN: %t-sse4.1-i8x16.cpp.bin | FileCheck %s
+
+// TODO!: ideally we need to introduce AVX2_HOST and similar features to
+// reliably test tests like this but for now assume that AVX2 is always
+// available practically on any x86_64 hosts
```
Comment (aneshlya) [inline tests/lit-tests/3513.ispc:86]: I hope this is true for all package managers builds of ISPC :)

**Review by aneshlya — APPROVED** [review]
LGTM!
