### PR TITLE
Fix build with LLVM trunk: moved `Instrumentation.h`

### LINKED ISSUE #3021: Build with LLVM trunk is broken: `llvm/Transforms/Instrumentation.h` has moved
Looks like the source of the problem is here: https://github.com/llvm/llvm-project/pull/108532

This is how the fail looks like:
https://github.com/ispc/ispc/actions/runs/10879023604/job/30192053329

Looks like we just need to use `llvm/Transforms/Utils/Instrumentation.h` instead of `llvm/Transforms/Instrumentation.h`

### LINKED ISSUE #3023: New LLVM API for instruction insertion
Starting 19.1 LLVM has introduced new API for inserting instructions, now it's based on `BasicBlock::iterator`, not on `Instruction *`. It's related to the changes in Debug Info representation. More information is available here: https://llvm.org/docs/RemoveDIsDebugInfo.html

Starting 20.0, they've deprecated old API, so it yields in numerous warnings.

The deprecation was enabled by this commit: https://github.com/llvm/llvm-project/commit/2f50b280dc8e995ef67ad31a5f71adc4c270890d

### PR DESCRIPTION
**Pull request by dbabokin**
Fixes #3021
Fixes #3023

Fix the build with LLVM trunk. Three different things are here:

- Update the include paths for Instrumentation headers (#3021)
- Update Instruction Insertion API. See #3023 for details
- Remove unneeded `-c` switch, which was triggering a warning on my system - this one is not related to `trunk`.

Please pay attention during review to Instruction Insertion API. New macros are a little verbose, but it's kinda intentional - we should remove them as soon as the lowest supported version is 19.1.

### CODE REVIEW

**Comment by dbabokin** [comment]
Waiting this pipeline to pass: https://github.com/ispc/ispc/actions/runs/10966524284

**Review by aneshlya — APPROVED** [review]
LGTM!

**Comment by dbabokin** [comment]
I've started a workflow to check the latest changes: https://github.com/ispc/ispc/actions/runs/10988007487

File: src/opt/ImproveMemoryOps.cpp [hunk 1]
```diff
@@ -188,14 +189,16 @@ static llvm::Value *lGetBasePtrAndOffsets(llvm::Value *ptrs, llvm::Value **offse
                         llvm::Value *zeroMask = llvm::ConstantVector::getSplat(
                             llvm::ElementCount::get(bop_var_type->getNumElements(), false),
                             llvm::Constant::getNullValue(llvm::Type::getInt32Ty(*g->ctx)));
-                        shuffle_offset = new llvm::ShuffleVectorInst(bop_var, llvm::UndefValue::get(bop_var_type),
-                                                                     zeroMask, "shuffle");
+                        shuffle_offset =
+                            new llvm::ShuffleVectorInst(bop_var, llvm::UndefValue::get(bop_var_type), zeroMask,
+                                                        "shuffle", ISPC_INSERTION_POINT_INSTRUCTION(bop_var));
```
Comment (aneshlya) [inline src/opt/ImproveMemoryOps.cpp:194]: This instruction is inserted twice now.

Comment (dbabokin) [reply src/opt/ImproveMemoryOps.cpp]: Good catch! That's an evil autocomplete in Cursor.

Comment (dbabokin) [reply src/opt/ImproveMemoryOps.cpp]: I've started a trunk-rebuild workflow as well: https://github.com/ispc/ispc/actions/runs/11020210568

Comment (dbabokin) [reply src/opt/ImproveMemoryOps.cpp]: Ok, CI fails are fixed, the benchmark fails are fix in a separate commit.

One more pipeline to verify that: https://github.com/ispc/ispc/actions/runs/11023557508

**Review by aneshlya — APPROVED** [review]
