### PR TITLE
Perform DIV and MOD binary operators only for active lanes

### LINKED ISSUE #1415: Integer divide crash with AVX
When compiling with AVX or AVX2 targets, the following crashes with integer divide by zero. SSE2 and SSE4 targets work as expected.

Compiled with 1.10.0 on Windows using -O2 and --target=avx or --target=avx

C++:
```
#include <cstdio>
#include "ISPCDivTest_ispc.h"

int main()
{
	const int Iterations = 16;
	int Dst[Iterations] = { 0 };
	int Src0[Iterations] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 };
	int Src1[Iterations] = { 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0 };

	ispc::Divi(Dst, Src0, Src1, Iterations);

	for (int i = 0; i < Iterations; i++)
	{
		printf("Dst[%d] = %d\n", i, Dst[i]);
	}
}
```

ISPC:
```
export void Divi(uniform int Dst[], uniform int Src0[], uniform int Src1[], uniform int Count)
{
	foreach(i = 0 ... Count)
	{
		bool bDivByZero = Src1[i] == 0;
		Dst[i] = bDivByZero ? 0 : Src0[i] / Src1[i];
	}
}
```

### PR DESCRIPTION
**Pull request by nurmukhametov**
This PR fixes #1415, #708, #2169, #2292.

### CODE REVIEW

**Comment by dbabokin** [comment]
Perf?

**Comment by nurmukhametov** [comment]
> Perf?

I haven't noticed a measurable impact. In cases where not all lanes are active, it should be faster than before.

File: src/ctx.cpp [hunk 1]
```diff
@@ -1668,6 +1767,13 @@ llvm::Value *FunctionEmitContext::BinaryOperator(llvm::Instruction::BinaryOps in
     int arraySize = lArrayVectorWidth(type);
 
     if (arraySize == 0) {
+        if (ispcType && ispcType->IsVaryingType() &&
+            (inst == llvm::Instruction::SDiv || inst == llvm::Instruction::UDiv || inst == llvm::Instruction::SRem ||
+             inst == llvm::Instruction::URem)) {
+            // TODO!: make sure we don't call it for uniform vectors
```
Comment (aneshlya) [inline src/ctx.cpp:1773]: Do you want to address this TODO in this PR?

File: src/ctx.h [hunk 2]
```diff
@@ -408,9 +409,20 @@ class FunctionEmitContext {
         See the Expressions section of docs/ispc.rst for more information on this
         optimization.
     */
-    llvm::Value *BinaryOperator(llvm::Instruction::BinaryOps inst, llvm::Value *v0, llvm::Value *v1,
+    llvm::Value *BinaryOperator(llvm::Instruction::BinaryOps inst, llvm::Value *v0, llvm::Value *v1, const Type *type,
```
Comment (aneshlya) [inline src/ctx.h:412]: Seems like you only need information about the variability of type for division operators, right?
Maybe you can just check `llvm::isa<llvm::VectorType>(v0->getType()) ` inside `BinaryOperator`?

The changes in this PR regarding the usage of the function are inconsistent. In some cases, a `nullptr` is passed (which makes sense when the type isn't related to division). In others, a non-null type is used even when it's unrelated to division—why include it there at all? And in some places, the code passes `type0` and then `type1`, even though they should be the same for binary operators.

File: src/ctx.cpp [hunk 3]
```diff
@@ -1656,8 +1639,124 @@ static int lArrayVectorWidth(llvm::Type *t) {
...
+// it. We need to perform division only for the active lanes. It is done by
+// calling builtin __idiv function. If all lanes are active, we can still use
+// the instction to divide the entire vector, which can be useful for
+// optimization when we divide compile time constants, e.g, programIndex
+// similar to the tests/lit-tests/2468.ispc.
+llvm::Value *FunctionEmitContext::VectorIntDivision(llvm::Instruction::BinaryOps inst, llvm::Value *v0, llvm::Value *v1,
+                                                    const llvm::Twine &name) {
+    // When handling vector division, we need to create a branching structure:
+    // If fullmask is all ON, use direct SDiv instruction
+    // Otherwise, use the __idiv intrinsic which handles masked division
```
Comment (aneshlya) [inline src/ctx.cpp:1706]: Could you remind me if we perform reciprocal optimization somewhere later? Like where the divisor has the same value across all vector lanes, we can just compute rcp and multiply.

File: tests/lit-tests/1415.ispc [hunk 4]
```diff
@@ -0,0 +1,53 @@
+// This test checks that generated code does not try to delete to zero.
```
Comment (aneshlya) [inline tests/lit-tests/1415.ispc:1]: divide by zero?

File: benchmarks/02_medium/test03_int_div.cpp [hunk 5]
```diff
@@ -0,0 +1,208 @@
...
+WARM_UP_RUN();
+
+// Minimum size is maximum target width * 4, i.e. 64*4 = 256.
+// 256 * sizeof (int) = 1kb - expected to reside in L1
+// 256 * sizeof (int) << 4 = 16kb - expected to reside in L1
+// 256 * sizeof (int) << 7 = 128kb - expected to reside in L2
+// 256 * sizeof (int) << 12 = 4 Mb - expected to reside in L3.
+#define ARGS Arg(256)->Arg(256 << 4)->Arg(256 << 7)->Arg(256 << 12)
+
+const float eps = 0.00001f;
```
Comment (aneshlya) [inline benchmarks/02_medium/test03_int_div.cpp:24]: This is not used anywhere

File: src/ctx.h (hunk 2 above)
Comment (nurmukhametov) [reply src/ctx.h:412]: > Seems like you only need information about the variability of type for division operators, right? Maybe you can just check `llvm::isa<llvm::VectorType>(v0->getType()) ` inside `BinaryOperator`?

Yes, I only need variability, but the suggested check gives incorrect answers for uniform short vectors because they are also represented as vectors in LLVM IR. This is why I need to pass around the proper ISPC type to check variability.

> The changes in this PR regarding the usage of the function are inconsistent. In some cases, a `nullptr` is passed (which makes sense when the type isn't related to division). In others, a non-null type is used even when it's unrelated to division—why include it there at all? And in some places, the code passes `type0` and then `type1`, even though they should be the same for binary operators.

In many cases, it is unclear to me what the ISPC type of the operands is. Moreover, in the current state of this function, the type parameter is used only for SDiv, UDiv, SRem, and URem operators. For any other operators, such as the frequent calls for And, Xor, and Or, it is not used, so passing a nullptr seems acceptable. I understand that this approach is somewhat unusual, but I haven't found a better solution to provide variability for the subset of required operators.

File: src/ctx.cpp (hunk 3 above)
Comment (nurmukhametov) [reply src/ctx.cpp:1714]: I have fixed the case when a divisor is a constant, and added the corresponding test `1415-2.ispc`, and benchmarks (fastdiv_mask).

File: src/ctx.h (hunk 2 above)
Comment (nurmukhametov) [reply src/ctx.h:418]: I have added a comment regarding this to the function declaration.

File: tests/lit-tests/1415.ispc (hunk 4 above)
Comment (aneshlya) [reply tests/lit-tests/1415.ispc]: There is still a "delete to zero." in a bunch of lit tests.

**Comment by aneshlya** [comment]
Looks good!

**Comment by illua1** [comment]
Wonder does this is by default on all platforms or only for whose support masked execution?

File: tests/lit-tests/1415.ispc (hunk 4 above)
Comment (nurmukhametov) [reply tests/lit-tests/1415.ispc]: Indeed, fixed.

**Review by aneshlya — APPROVED** [review]
