### PR TITLE
Fix internal error when casting SOA pointer to opaque pointer (#3591)

### LINKED ISSUE #3591: Internal error casting `soa<>` pointer to opaque pointer
The following reproducer:
```ispc
struct point {
    int x, y;
};

struct foo;

__attribute__((external_only))
export foo* uniform foo_init() {
    soa<8> point* uniform points = uniform new soa<8> point[123];
    return (foo* uniform)points;
}
```
causes the following crash:
```text
$ ispc --version
Intel(r) Implicit SPMD Program Compiler (Intel(r) ISPC), 1.28.2 (build commit 5bf8fb90b34122b5 @ 20250925, LLVM 20.1.8)
$ ispc test.ispc
Warning: No output file or header file name specified. Program will be compiled and warnings/errors will be issued, but no output will be generated. 
Warning: No --target specified on command-line. Using default system target "avx2-i32x8". 
Invalid bitcast
  %17 = bitcast { ptr, i32 } %16 to ptr
Invalid bitcast
  %27 = bitcast { ptr, i32 } %26 to ptr
LLVM ERROR: Broken module found, compilation aborted!
/usr/src/debug/ispc/ispc/src/main.cpp(40): FATAL ERROR: Unhandled signal sent to process; terminating.
***
*** Please file a bug report at https://github.com/ispc/ispc/issues
*** (Including as much information as you can about how to reproduce this error).
*** You have apparently encountered a bug in the compiler that we'd like to fix!
***
Aborted                    (core dumped) ispc test.ispc
```

### PR DESCRIPTION
**Pull request by aneshlya**
When casting a slice/SOA pointer (e.g., soa<8> point* uniform) to an opaque pointer type (e.g., foo* uniform), the compiler was attempting to bitcast the entire slice pointer structure ({ptr, i32}) directly to a simple pointer (ptr), which is invalid in LLVM.

The fix extracts the pointer component from the slice structure before performing the bitcast, allowing the cast to succeed.

Fixes #3591

## Checklist
- [x] Code has been formatted with `clang-format` (e.g., `clang-format -i src/ispc.cpp`)
- [x] Git history has been squashed to meaningful commits (one commit per logical change)
- [x] Compiler changes are covered by [lit tests](https://github.com/ispc/ispc/tree/main/tests/lit-tests)
- [ ] Language/stdlib changes include new [functional tests](https://github.com/ispc/ispc/tree/main/tests/func-tests) for runtime behavior
- [ ] [Documentation](https://github.com/ispc/ispc/tree/main/docs/ispc.rst) updated if needed

### CODE REVIEW

**Comment by aneshlya** [comment]
@codex review

**Comment by aneshlya** [comment]
@codex review

File: src/expr.cpp [hunk 1]
```diff
@@ -8028,7 +8028,13 @@ const Type *TypeCastExpr::GetLValueType() const {
 static const Type *lDeconstifyType(const Type *t) {
     const PointerType *pt = CastType<PointerType>(t);
     if (pt != nullptr) {
-        return new PointerType(lDeconstifyType(pt->GetBaseType()), pt->GetVariability(), false);
+        // Preserve slice property when removing constness
```
Comment (nurmukhametov) [inline src/expr.cpp:8039]: IIRC, types system has `AsNonConstType` implemented for every type. Why do we need this local helper here instead of properly implemented method for PointetType (if the current one is not suitable)?

Comment (aneshlya) [reply src/expr.cpp:8039]: It's a good question. Looks like `PointerType, GetAsNonConstType()` removes the const qualifier from the pointer itself, not from what it points to.
`lDeconstifyType` removes `const` from what the pointer points to.

Comment (nurmukhametov) [reply src/expr.cpp:8039]: Right, so this function removes const from both pointer and pointee type for pointer types.

**Review by nurmukhametov — APPROVED** [review]
LGTM!
